config:
  default:
    keys: 'lee6'
    security:
      csrf:
        enable: false
    siteFile:
      /favicon.ico: 'https://github.com/fluidicon.png'
    static:
      prefix: '/'
      dir: 'dist'
      gzip: true
      usePrecompiledGzip: true,
      maxAge: 31536000
    githubWebhook:
      path: '/'
      secret: '...'
      event:
        push: './scripts/githook.js'
    alinode:
      enable: true
      appid: '79920'
      secret: 'ee24acff05a47fa4b92539bb870e4a951e1d98a9'
plugin:
  index:
    enable: true
    package: 'egg-index'
  githubWebhook:
    enable: true
    package: 'egg-github-webhook'
  rewriter:
    enable: true
    package: 'egg-rewriter'
  alinode:
    enable: true
    package: 'egg-alinode'
