config:
  default:
    keys: 'dearred'
    static:
      prefix: '/'
      dir: 'dist'
      gzip: true
      usePrecompiledGzip: true,
      maxAge: 31536000
plugin:
  index:
    enable: true
    package: 'egg-index'
