config:
  default:
    keys: 'dearred'
    security:
      csrf:
        enable: false
    static:
      prefix: '/'
      dir: 'dist'
      gzip: true
      usePrecompiledGzip: true,
      maxAge: 31536000
    githubWebhook:
      path: '/'
      secret: '...'
      event:
        push: './scripts/githook.js'
plugin:
  index:
    enable: true
    package: 'egg-index'
  githubWebhook:
    enable: true
    package: 'egg-github-webhook'
