version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          filters:
            branches:
              only: master
          steps:
            - run: npm install
      - run: sh deploy-circleci.sh
