version: 2.1
jobs:
  run_install:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-{{ .Branch }}-
            - v1-
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  run_build:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Build
          command: |
            npm run build

workflows:
  build_deploy:
    jobs:
      - run_install
      - run_build:
          filters:
            branches:
              only:
                - master
          requires:
            - run_install
