version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - cache-{{ .Branch }}-
            - cache-
      - run: npm install
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  build:
    steps:
      - run: npm run build

  deploy:
    steps:
      - run: npm run test:e2e -- --env phantomjs
      - run: git config --global user.email "$EMAIL"
      - run: git config --global user.name "$NAME"
      - run: git add -f home
      - run: git commit -m "build"
      - run: git push

workflows:
  version: 2
  install-build-and-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - "master"
