version: 2.1
jobs:
  run_install:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
  run_build:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Build
          command: |
            npm run build

workflows:
  build_deploy:
    jobs:
      - run_install
