version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - checkout
            - node/with-cache:
                steps:
                  - run: npm install --legacy-peer-deps
                  - run: sh deploy-circleci.sh
