version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install --legacy-peer-deps
      - run: sh deploy-circleci.sh
workflows:
  version: 2
    build-deploy:
      jobs:
        - build:
            filters:
              branches:
                only: master
