version: 2.1

defaults: &defaults
  working_directory: ~/project/app
  docker:
    - image: circleci/node:12

jobs:
  run_install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-{{ .Branch }}-
            - v1-
      - run: yarn
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - app
  run_build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build
  run_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
  run_lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint
  run_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm test

workflows:
  build_deploy:
    jobs:
      - run_install:
          filters:
            branches:
              only:
                - master
      - run_build:
          filters:
            branches:
              only:
                - master
          requires:
            - run_install
      - run_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - run_build
      - run_lint:
          requires:
            - run_install
      - run_test:
          requires:
            - run_install
