version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12

jobs:
  run_build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-{{ .Branch }}-
            - v1-
      - run: yarn
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run: yarn build

workflows:
  build_deploy:
    jobs:
      - run_build:
          filters:
            branches:
              only:
                - master
